apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    events {}

    http {
        server {
            listen       80;
            location / {
                proxy_pass   http://ifconfig.me/;
            }
        }
    }
